[Interface]
Address = 10.8.0.2/24
PrivateKey = sDRfWJuGZnTnGi67LC27MXaJk3JWO7Okc20sMSNK+2s=
DNS = 1.1.1.1

[Peer]
PublicKey = rG8oLk8pK/1V2t6qvYhSxjgWZBP5oC1smJGje0szIFc=
PresharedKey = Qu6/pcKHhHtSvoPwTSkrPX00gS74QJGVnZK9oIUGDds=
Endpoint = 2003:eb:1f28:c900:dea6:32ff:fea1:f156:51820
AllowedIPs = 10.8.0.0/24
PersistentKeepalive = 25
